create table Batch
(
    create_time timestamp(6),
    id          bigint generated by default as identity,
    update_time timestamp(6),
    primary key (id)
);

create table Bill
(
    create_time timestamp(6),
    id          bigint generated by default as identity,
    update_time timestamp(6),
    primary key (id)
);

create table Category
(
    create_time timestamp(6),
    id          bigint generated by default as identity,
    update_time timestamp(6),
    primary key (id)
);

create table Contract
(
    create_time timestamp(6),
    id          bigint generated by default as identity,
    update_time timestamp(6),
    primary key (id)
);

create table Customer
(
    create_time timestamp(6),
    id          bigint generated by default as identity,
    update_time timestamp(6),
    primary key (id)
);

create table Employee
(
    active      boolean,
    dob         date,
    create_time timestamp(6),
    id          bigint generated by default as identity,
    update_time timestamp(6),
    address     varchar(255),
    district    varchar(255),
    email       varchar(255) not null unique,
    full_name   varchar(255) not null,
    gender      varchar(255),
    note        varchar(255),
    password    varchar(255) not null,
    phone       varchar(255) unique,
    province    varchar(255),
    primary key (id)
);

create table employee_roles
(
    employee_id bigint not null,
    roles_id    bigint not null,
    primary key (employee_id, roles_id)
);

create table Invoice
(
    create_time timestamp(6),
    id          bigint generated by default as identity,
    update_time timestamp(6),
    primary key (id)
);

create table orders
(
    create_time timestamp(6),
    id          bigint generated by default as identity,
    update_time timestamp(6),
    primary key (id)
);

create table Permission
(
    create_time timestamp(6),
    update_time timestamp(6),
    description varchar(255),
    name        varchar(255) not null,
    primary key (name)
);

create table Product
(
    create_time timestamp(6),
    id          bigint generated by default as identity,
    update_time timestamp(6),
    primary key (id)
);

create table Purchase
(
    create_time timestamp(6),
    id          bigint generated by default as identity,
    update_time timestamp(6),
    primary key (id)
);

create table Role
(
    create_time timestamp(6),
    id          bigint generated by default as identity,
    update_time timestamp(6),
    description varchar(255),
    name        varchar(255) not null unique,
    primary key (id)
);

create table role_permissions
(
    role_id         bigint       not null,
    permission_name varchar(255) not null,
    primary key (role_id, permission_name)
);

create table Store
(
    create_time timestamp(6),
    id          bigint generated by default as identity,
    update_time timestamp(6),
    primary key (id)
);

create table Vendor
(
    create_time timestamp(6),
    id          bigint generated by default as identity,
    update_time timestamp(6),
    primary key (id)
);

alter table if exists employee_roles
    add constraint FK7cwh4c9tya2q8p875bl2df9ms
        foreign key (roles_id)
            references Role;

alter table if exists employee_roles
    add constraint FKqcoxeuu6o7la3lbt5o7iqpxjw
        foreign key (employee_id)
            references Employee;

alter table if exists role_permissions
    add constraint FKfkw8fs9vs83odestj49j7p93r
        foreign key (permission_name)
            references Permission;

alter table if exists role_permissions
    add constraint FKkhiunnkn7uytm6cbnk1pe6qo0
        foreign key (role_id)
            references Role;
